-- Creates the checkin_link_tokens table for time-limited, unauthenticated kiosk access URLs.
-- These tokens are generated by managers, sent to the team via email, and expire in 24 hours.
-- All access via these tokens is still audit-logged in time_entries.

CREATE TABLE IF NOT EXISTS checkin_link_tokens (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  token       TEXT        UNIQUE NOT NULL,
  event_id    UUID        NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  created_by  UUID        REFERENCES users(id) ON DELETE SET NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at  TIMESTAMPTZ,
  last_used_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS checkin_link_tokens_token_idx    ON checkin_link_tokens (token);
CREATE INDEX IF NOT EXISTS checkin_link_tokens_event_id_idx ON checkin_link_tokens (event_id);

-- All operations happen server-side via the service role key.
-- No client-side (anon/authenticated user) access is needed.
ALTER TABLE checkin_link_tokens ENABLE ROW LEVEL SECURITY;
